### ISSUE TITLE
我的屏幕只支持IIC，为什么还要适配SPI

### ISSUE THREAD

**Issue by ThinkCodeStudio** [hepingood/ssd1306#3]
是为什么要留两两种接口的函数指针，我只用IIC 还有必要写SPI的函数吗，删掉SPI怎么样

**Comment by hepingood** [comment]
Hello, SSD1306 chip supports IIC and SPI interfaces, so we provide drivers for both interfaces. If you only use the IIC interface, you can not implement the SPI interface of your application platform (just return 1 directly). When you call the driver, select the IIC interface, and the driver will not call any part of SPI.

您好，SSD1306芯片支持IIC与SPI两种接口，所以我们提供两种接口的驱动。如果您只使用IIC接口，可以不实现您应用平台的SPI接口（直接返回1即可）。您在调用驱动时候选择IIC接口，驱动不会调用任何SPI的部分。
